name: .NET

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: |
        dotnet build --no-restore -c Debug
        dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Upload test results
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: './FastLuaTest/TestResults/*'
        flags: unittests
        name: codecov
        fail_ci_if_error: true
        verbose: false
    - name: Benchmark
      run: dotnet run -c Release --project FastLuaBenchmark
      
