name: .NET

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build_debug --no-restore -o build -c Debug
    - name: Build Release
      run: dotnet build_release --no-restore -o build -c Release
    - name: Test
      run: dotnet test build_debug/FastLuaTest.dll --no-build --verbosity normal
    - name: Benchmark
      run: dotnet build_release/FastLuaBenchmark.dll
      
